server:
  servlet:
    context-path: /assaservice

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_J4ddaevai
  datasource:
    username: admin
    password: Pocassembly2023*.
    url: jdbc:mariadb://database-1.cnmfw4cuoaxi.us-east-1.rds.amazonaws.com:3306/assaabloy
    driver-class-name=org: org.mariadb.jdbc.Driver

assacredential:
  api:
    baseUrl: https://onboarding.credential-services.api.assaabloy.com
    username: Globant-demo-tenant
    password: 7bc8f976-deb4-3924-851f-225c26c11761

assavisionline:
  api:
    baseUrl: https://ec2-54-147-239-148.compute-1.amazonaws.com
    username: sym 
    password: sym 

cognitoidp:
    region: us-east-1
    pool: us-east-1_J4ddaevai


logging:
  level:
    root: INFO
    org.springframework: ERROR
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan}[%5.5line]%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"


